# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile_test.yml                                  :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/05 16:00:54 by umeneses          #+#    #+#              #
#    Updated: 2025/01/05 08:39:23 by umeneses         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Makefile Test

on:
  push:
    branches:
    - main
    - '**feature**'
    - '**feat**'
    - '**bugfix**'
    - '**fix**'
    - '**release**'
  pull_request:
    branches:
    - main
    - '**feature**'
    - '**feat**'
    - '**bugfix**'
    - '**fix**'
    - '**release**'

jobs:
  Makefile-test:
    runs-on: ubuntu-latest
    timeout-minutes: 7
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Starting Github Actions
        uses: actions/checkout@v4.1.4

      - name: Install Aptitude
        run: sudo apt-get install aptitude

      - name: Install GLFW Library
        run: sudo aptitude install libglfw3 libglfw3-dev libglfw3-doc -y

      # - name: Install Aptitude
      #   run: sudo apt-get install aptitude

      # - name: Install Valgrind
      #   run: sudo aptitude install -y valgrind

      # - name: Submodule Init
      #   run: git submodule init && git submodule update

      - name: Building Program with Cube3D Makefile
        run: make
