# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    mlx_all_maps_valgrind.yml                          :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/14 16:00:54 by umeneses          #+#    #+#              #
#    Updated: 2025/04/21 22:30:15 by copilot          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: Cub3D Memory Leak Test

on: [push, pull_request]

jobs:
  cub3d-memory-test:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      my_valgrind: >
        valgrind --leak-check=full --track-origins=yes --show-leak-kinds=all
        --show-reachable=yes --suppressions=mlx_suppressions_actions.sup

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential valgrind
        sudo apt-get install -y libglfw3 libglfw3-dev libglfw3-doc
        sudo apt-get install -y xvfb x11-utils xdotool

    - name: Compile Cube3D with make
      run: make

    - name: Create Timeout Signal Handler
      run: |
        # Create a patched handle_keypress.c that will exit after a timeout
        cat << 'EOF' > signal_handler.c
        #include <signal.h>
        #include <stdio.h>
        #include <stdlib.h>
        
        void handle_usr1(int sig) {
            printf("Received SIGUSR1, exiting cleanly...\n");
            exit(EXIT_SUCCESS);
        }
        
        void setup_signal_handler() {
            signal(SIGUSR1, handle_usr1);
        }
        EOF
        
        # Add this to your compilation if needed, or inject via LD_PRELOAD

    - name: Run Memory Test
      run: |
        # Start virtual display
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        sleep 2
        
        # Create test script
        cat << 'EOF' > test_memory.sh
        #!/bin/bash
        
        # Setup better X environment
        export DISPLAY=:99
        export LIBGL_ALWAYS_SOFTWARE=1
        export MESA_GL_VERSION_OVERRIDE=3.3
        
        # Start the game with valgrind
        ${my_valgrind} ./cub3d ./maps/default.cub > valgrind_output.log 2>&1 &
        GAME_PID=$!
        
        # Give the game time to initialize (10 seconds)
        echo "Waiting for game to initialize (10 seconds)..."
        sleep 10
        
        # Try window detection
        if xdotool search --name "Cub3D" >/dev/null; then
          WINDOW_ID=$(xdotool search --name "Cub3D" | head -1)
          echo "Found game window with ID: $WINDOW_ID"
          
          # Try to send ESC key via multiple methods
          echo "Attempting to send ESC key..."
          xdotool key --window $WINDOW_ID Escape
          sleep 1
          xdotool windowfocus $WINDOW_ID
          xdotool key --clearmodifiers Escape
          sleep 1
        else
          echo "Window not found by name. Will use signals."
        fi
        
        # Send clean termination signal
        echo "Sending termination signal to game (PID: $GAME_PID)"
        kill -USR1 $GAME_PID
        sleep 2
        
        # If still running, try SIGTERM
        if kill -0 $GAME_PID 2>/dev/null; then
          echo "Game still running. Sending SIGTERM."
          kill -TERM $GAME_PID
          sleep 2
        fi
        
        # If still running, force kill
        if kill -0 $GAME_PID 2>/dev/null; then
          echo "Game still running. Force killing."
          kill -9 $GAME_PID
        fi
        
        # Wait for valgrind to finish writing
        sleep 2
        
        # Display valgrind output with proper formatting
        echo ""
        echo "===== VALGRIND REPORT ====="
        cat valgrind_output.log
        
        # Extract and display the leak summary for clarity
        echo ""
        echo "===== LEAK SUMMARY ====="
        grep -A 10 "LEAK SUMMARY" valgrind_output.log
        
        # Check for memory leaks with specific reporting
        if grep -q "definitely lost: [^0]" valgrind_output.log; then
          echo "❌ DEFINITELY LOST memory detected!"
          exit 1
        elif grep -q "indirectly lost: [^0]" valgrind_output.log; then
          echo "❌ INDIRECTLY LOST memory detected!"
          exit 1
        elif grep -q "possibly lost: [^0]" valgrind_output.log; then
          echo "⚠️ POSSIBLY LOST memory detected (not failing the build)"
        elif grep -q "still reachable: [^0]" valgrind_output.log; then
          echo "ℹ️ STILL REACHABLE memory detected (not failing the build)"
        else
          echo "✅ No memory leaks detected!"
        fi
        
        # Check for other valgrind errors
        if grep -q "ERROR SUMMARY: [^0]" valgrind_output.log; then
          echo "❌ Valgrind detected errors!"
          exit 1
        else
          echo "✅ No valgrind errors detected!"
        fi
        EOF
        
        # Make script executable and run it
        chmod +x test_memory.sh
        ./test_memory.sh

