# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    norminette.yml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: umeneses <umeneses@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/14 16:00:54 by umeneses          #+#    #+#              #
#    Updated: 2025/01/05 08:39:23 by umeneses         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name: norminette

on:
  push:
    branches:
    - main
    - '**feature**'
    - '**feat**'
    - '**bugfix**'
    - '**fix**'
    - '**release**'
  pull_request:
    branches:
    - main
    - '**feature**'
    - '**feat**'
    - '**bugfix**'
    - '**fix**'
    - '**release**'

jobs:
  norminette:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Replace main.c
        run: |
          cp ./.github/workflows/main_for_actions.c ./src/01.main.c

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install Python for Norminette
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: python -m pip install --upgrade pip setuptools

      - name: Install Norminette
        run: python -m pip install norminette

      - name: Running Norminette with Failure Counter
        run: |
          failed_count=0
          for file in $(find ./headers ./libs/libft ./src -name '*.c' -o -name '*.h'); do
            if ! norminette -R CheckForbiddenSourceHeader "$file"; then
              failed_count=$((failed_count + 1))
            fi
          done

          if [ "$failed_count" -gt 0 ]; then
            echo "😭 😭 😭 "
            echo -e "\033[1;31mNorminette failed for $failed_count file(s)\033[0m"
            exit 1
          else
            echo "🎊 🎊 🎊"
            echo "😎 😎 😎"
            echo "🎉 🎉 🎉"  
            echo -e "\033[1;32mAll files passed Norminette\033[0m"
          fi

# :: github actions documentation ::
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
